// This file is automatically generated by tools.
// To update all exports inside project
// run :
// genexp

export 'dashboard_page.dart';
export 'detail_movie_page.dart';
export 'search_page.dart';
export 'splash_page.dart';
